Feature/initial integration
JupiterOne/graph-jenkins pull request #4
Opened 2022-06-29 17:55 UTC by eXtremeX

## Summary

- Ingest new entities
  - `jenkins_account`
  - `jenkins_build`
  - `jenkins_job`
  - `jenkins_repository`
  - `jenkins_role`
  - `jenkins_user`
  
- Build new relationships
  - `jenkins_account_has_job`
  - `jenkins_account_has_role`
  - `jenkins_account_has_user`
  - `jenkins_build_has_repository`
  - `jenkins_job_has_build`
  - `jenkins_job_has_job`
  - `jenkins_user_assigned_role`
  - `jenkins_user_has_build`

## Type of change

Please leave any irrelevant options unchecked.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [x] This change requires a documentation update

## Checklist

### General Development Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### Integration Development Checklist:

Please leave any irrelevant options unchecked.

- [x] I have checked for additional permissions required to call any new API
      endpoints, and have documented any additional permissions in
      `jupiterone.md`, where necessary.
- [x] My changes properly paginate the target service provider's API
- [x] My changes properly handle rate limiting of the target service provider's
      API
- [x] My new integration step is instrumented to execute in the correct order
      using `dependsOn`
- [x] I have referred to the
      [JupiterOne data model](https://github.com/JupiterOne/data-model/tree/main/src/schemas)
      to ensure that any new entities/relationships, and relevant properties,
      match the recommended model for this class of data
- [x] I have updated the `CHANGELOG.md` file to describe my changes
- [x] When changes include modifications to existing graph data ingestion, I've
      reviewed all existing managed questions referencing the entities,
      relationships, and their property names, to ensure those questions still
      function with my changes.

2022-06-30 09:13 UTC, neurovelho approved these changes

2022-06-30 09:13 UTC, neurovelho commented on src/steps/build/converter.ts
> +  }
Could be replaced with `arr.find`.

2022-07-19 01:08 UTC, austinkelleher requested changes

2022-07-19 01:08 UTC, austinkelleher commented on src/steps/user/index.ts
> +    const userEntity = await jobState.addEntity(createUserEntity(user));
This is producing a duplicate key against our prod Jenkins instance. Is there a more unique `_key` than this? https://github.com/JupiterOne/graph-jenkins/pull/4/files#diff-af8ebd7417e323249847fbfa1033c3d21088dafe73fc1d4b3c087454bed8570cR15

2022-07-19 01:13 UTC, austinkelleher commented on src/client.ts
> +          `/role-strategy/strategy/getAllRoles?type=${roleType}`,
I'm seeing a 403 when running this against our prod Jenkins instance with my user. I wonder if this API requires admin permissions? If so, can we please document that and ensure that this step emits a job log event that indicates the necessary permission?

2022-07-19 01:25 UTC, austinkelleher commented on src/steps/repository/converter.ts
> +        url: repository.url,
Would be nice if we could build a `webLink` from this. I understand that these can be Git URLs.

2022-07-19 01:27 UTC, austinkelleher commented on src/steps/job/converter.ts
> +        url: project.url,
```suggestion
        webLink: project.url,
```

2022-07-19 01:30 UTC, austinkelleher commented on .github/workflows/gitleaks.yml
> +        uses: gitleaks/gitleaks-action@v1.6.0
FYI we now are using GitHub Enterprise which has built-in secrets scanning. We can completely remove this file and the top level `.gitleaks.yml` file

Here is an example PR: https://github.com/JupiterOne/graph-asana/pull/11

2022-07-19 01:32 UTC, austinkelleher commented on docs/development.md
> +3. Create an admin account on this installation
I don't know whether an admin is truly necessary. My user in our prod Jenkins instance is _not_ an admin and was able to collect most of the data. I made a comment below about the inability to collect role data.

2022-07-27 14:36 UTC, eXtremeX commented on src/steps/user/converter.ts
> +        lastChange: users.lastChange,
Looks that way, however I wasn't able to see any value in the lastChange value after modifying my user :thinking: 
Do you happen to have a raw data that shows what that value might look like? (I'd want to use the helper `parseTimePropertyValue` function if possible)

2022-07-27 16:20 UTC, eXtremeX commented on src/steps/user/converter.ts
> +        lastChange: users.lastChange,
Update: saw response blob over Slack, so no longer needed

2022-08-29 13:04 UTC, neurovelho commented
@austinkelleher Just FYI, I added a Dockerfile (modified from graph-kubernetes), that can be used to build an image capable of running this integration in a Jenkins pipeline.

Here's an example pipeline:

```
pipeline {
    agent {
        docker { image 'creativicedev/graph-jenkins:0.0.0' }
    }
    
    environment {
        JUPITERONE_API_KEY = 'j1_api_key'
        JUPITERONE_ACCOUNT = 'j1_account'
        USER_NAME = 'jenkins_username'
        API_KEY   = 'jenkins_api_key'
        HOST_NAME = 'http://172.17.0.1:8080'
    }
    
    stages {
        stage('Test') {
            steps {
                sh 'cd /opt/jupiterone/integration && yarn start'
            }
        }
    }
}
```

2022-09-12 11:58 UTC, austinkelleher commented on docs/jupiterone.md
> +### In Jenkins
👍 Thanks for adding docs about this!

2022-09-13 19:12 UTC, austinkelleher approved these changes

2022-09-30 22:05 UTC, VDubber commented on docs/spec/src/build/index.ts
> +  // {
@eXtremeX From a team meeting, I believe we will never want to support the ingestion of jenkin jobs - too much data :) 

Please remove all commented code relating to job ingestion

2022-10-05 18:32 UTC, mdaum commented
Thanks for all this work! Looks like we need to merge `main` into this branch and we should be good to go!. I just finished adding image build/publish workflow setup for this repo. So an image should be published when we merge this to `main`, and when we cut a new version 👍

2022-10-10 19:36 UTC, adam-in-ict approved these changes

2022-10-10 19:49 UTC, merged